### ISSUE TITLE
EASTRON SDM630 MODBUS-MID V2 Request

### ISSUE THREAD

**Issue by solarc3po** [kbialek/deye-inverter-mqtt#126]
Dear KBialek, many thanks for your exelent work and effort. 

As I see in one of the last releases you provide support for an dtsd422 smart meter.
As I know a lot of user using EASTRON SDM630 MODBUS-MID V2. 
Do you think its possible to inklude reading data from this meter also in the docker image?

Many Thank & Best Regards
Frank

**Comment by kbialek** [comment]
hi @solarc3po 

> As I know a lot of user using EASTRON SDM630 MODBUS-MID V2.
> Do you think its possible to inklude reading data from this meter also in the docker image?

No, this is not possible, because of two reasons. This project only supports devices that:
1. Communicate over ethernet using Modbus/TCP (or Modbus/AT). EASTRON SDM630 uses Modbus/RTU over RS485. Supporting it would require adding serial port integration, which is beyond the scope of this project.
2. Are compatible with protocol used by Deye inverters and their clones.
