### ISSUE TITLE
Publish units next to values

### ISSUE THREAD

**Issue by aperiodicchain** [kbialek/deye-inverter-mqtt#153]
Deye SUN-15K-SG01HP3-EU-AM2 works nicely and I can consume mqtt topics.

I am getting values like so:
```python
{'name': 'dc/pv1/power', 'value': 650}
{'name': 'dc/pv2/power', 'value': 1470}
{'name': 'dc/pv1/voltage', 'value': 367.40000000000003}
```
What I am missing are the units (Watt, A, kWh,...). 
I have checked that units are well defined in e.g.: deye_sensors_deye_sg01hp3.py 
so I think they just have not been implemented for the mqtt_publisher (by choice?).

Can anyone please briefly confirm? If I want units to be published as well, so `{'name': 'dc/pv1/power', 'value': 650, 'unit':'Watt'}` do I have to create a plugin or is there a simpler way? 

**Hardware (please complete the following information):**
 - Inverter model: Deye SUN-15K-SG01HP3-EU-AM2

**Software (please complete the following information):**
 - Logger firmware version: 0104 HMI：2001-C01F
 - deye-inverter-mqtt version: latest master
 - config.env (remove passwords before pasting):
```.env
DEYE_LOGGER_IP_ADDRESS=192.168.168.43
DEYE_LOGGER_SERIAL_NUMBER=2xxxxxxxx3
MQTT_HOST=192.168.168.41
LOG_LEVEL=DEBUG # INFO
# LOG_STREAM=STDOUT
DEYE_METRIC_GROUPS=deye_sg01hp3,deye_sg01hp3_battery,deye_sg01hp3_bms
```

**Comment by kbialek** [comment]
@aperiodicchain MQTT does not have a concept of message's value unit. In MQTT, a message payload is simply an array of bytes.
Your problem could be solved by using structured message payload, that contains the value and the unit , e.g. in JSON format `{ "value": 123, "unit":"V" }`
You are right, to achieve this goal, you will have to implement a custom MQTT publishing plugin, and use it instead of the default, built-in one.
